steps:
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_API_URL=https://artefacto-backend-749281711221.us-central1.run.app/api'
      - 'VITE_ML_API_URL=https://artefacto-backend-749281711221.us-central1.run.app/api/ml'
      - 'NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        if [ ! -f dist/index.html ]; then
          echo "Build failed: index.html not found"
          exit 1
        fi
        echo "Deploying to App Engine..."
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy --quiet

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY

